"""add parent_id and is_active column as nullable

Revision ID: 1c306ba63c6d
Revises: ff3ddca5a9ac
Create Date: 2026-04-16 10:11:50.276862

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c306ba63c6d'
down_revision: Union[str, Sequence[str], None] = 'ff3ddca5a9ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('parent_id', sa.Integer(), nullable=True))
    op.add_column('categories', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.alter_column('categories', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_constraint(op.f('categories_name_key'), 'categories', type_='unique')
    op.create_foreign_key(None, 'categories', 'categories', ['parent_id'], ['id'])

    # FILL IN THE DATA FOR EXISTING RECORDS.
    op.execute("UPDATE categories SET is_active = true WHERE is_active IS NULL")

    # IMPLEMENT THE NOT NULL CONSTRAINT.
    op.alter_column('categories', 'is_active', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'categories', type_='foreignkey')
    op.create_unique_constraint(op.f('categories_name_key'), 'categories', ['name'], postgresql_nulls_not_distinct=False)
    op.alter_column('categories', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('categories', 'is_active')
    op.drop_column('categories', 'parent_id')
    # ### end Alembic commands ###
