"""Initial migration for PostgreSQL

Revision ID: ff3ddca5a9ac
Revises: 0c263dbd7045
Create Date: 2026-04-13 23:42:38.124767

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff3ddca5a9ac'
down_revision: Union[str, Sequence[str], None] = '0c263dbd7045'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
